Repository kookmin-sw/capstone-2020-12, pull requests merged in 2020-04, with the labels that each got.

#13 GraphQL 스키마 디자인 완료
  src/server/Pipfile
  src/server/Pipfile.lock
  src/server/schema.graphql
Labels: Back-end, Scaffolding

#19 백엔드 pre-alpha 버전 완성
  src/server/Pipfile
  src/server/Pipfile.lock
  src/server/README.md
  src/server/app.py
  src/server/mock_data.py
  src/server/resolvers/__init__.py
  src/server/resolvers/media.py
  src/server/resolvers/query.py
  src/server/resolvers/video.py
  src/server/schema.graphql
Labels: Back-end, Scaffolding

#14 Mediadetail UI component
  src/web/package.json
  src/web/src/components/media-detail-card-query.js
  src/web/src/components/media-detail-card.js
  src/web/src/components/media-detail-delete-button.js
  src/web/src/pages/media-detail-page.js
Labels: Front-end, enhancement

#30 feat(uploadMedia): uploadMedia mutation 구현
  src/server/app.py
  src/server/mock_data.py
  src/server/resolvers/__init__.py
  src/server/resolvers/mutation.py
  src/server/resolvers/query.py
Labels: Back-end

#32 feat(delete-media): deleteMedia mutation 구현
  src/server/resolvers/mutation.py
  src/server/resolvers/query.py
Labels: Back-end

#33 feat(Author): Author정보를 받아올 수 있게 수정
  src/server/app.py
  src/server/mock_data.py
  src/server/resolvers/query.py
  src/server/resolvers/video.py
  src/server/schema.graphql
Labels: Back-end

#36 Topnavbar b
  src/server/mock_db.dump
  src/web/package.json
  src/web/src/Image/memories_logo.jpg
  src/web/src/Screen/HomeScreen.js
  src/web/src/Screen/SearchScreen.js
  src/web/src/components/Header.js
  src/web/src/components/HeaderIcons.js
  src/web/src/components/HeaderLogo.js
  src/web/src/components/SearchBar.js
  src/web/src/components/SearchBarInput.js
  src/web/src/components/SearchBarPlaceSelect.js
  src/web/src/components/SearchBarSubmitButton.js
  src/web/src/components/SearchBarYearSelect.js
Labels: Front-end

#37 media detail query 구현
  src/web/src/components/media-detail-card-query.js
  src/web/src/components/media-detail-card.js
  src/web/src/components/media-detail-delete-button.js
  src/web/src/pages/media-detail-page.js
Labels: Front-end, enhancement

#39 query parameter 적용
  src/web/src/components/SearchBarSubmitButton.js
Labels: Front-end, enhancement

#40 web Media delete 기능 구현
  src/web/src/components/error-view.js
  src/web/src/components/media-detail-card-query.js
  src/web/src/components/media-detail-delete-button.js
  src/web/src/pages/media-view-page.js
Labels: Front-end, enhancement

#41 upload pages/MediaListPage.js
  src/web/src/components/MediaList/MediaCard.js
  src/web/src/pages/MediaListPage.js
Labels: Front-end, enhancement

#42 upload page
  package-lock.json
  src/web/package-lock.json
  src/web/package.json
  src/web/src/App.js
  src/web/src/components/UploadPage/DropzoneBox.js
  src/web/src/components/UploadPage/InputFile.js
  src/web/src/components/UploadPage/UploadDateSelect.js
  src/web/src/components/UploadPage/UploadDescription.js
  src/web/src/components/UploadPage/UploadPageTitle.js
  src/web/src/components/UploadPage/UploadPlaceSelect.js
  src/web/src/components/UploadPage/UploadSubmitButton.js
  src/web/src/pages/UploadPage.js
Labels: Front-end, bug, help wanted

#44 Component integrate
  src/web/src/App.js
  src/web/src/components/HeaderIcons.js
  src/web/src/components/UploadPage/DropzoneBox.js
  src/web/src/components/UploadPage/InputFile.js
  src/web/src/components/UploadPage/UploadDateSelect.js
  src/web/src/components/UploadPage/UploadDescription.js
  src/web/src/components/UploadPage/UploadPageTitle.js
  src/web/src/components/UploadPage/UploadPlaceSelect.js
  src/web/src/components/UploadPage/UploadSubmitButton.js
  src/web/src/components/error-view.js
  src/web/src/components/media-detail-card-query.js
  src/web/src/components/media-detail-card.js
  src/web/src/components/media-detail-delete-button.js
  src/web/src/index.js
  src/web/src/pages/MediaListPage.js
  src/web/src/pages/UploadPage.js
  src/web/src/pages/media-view-page.js
Labels: Front-end

#50 layout center로 변경
  src/web/src/pages/media-view-page.js
Labels: Front-end

#60 시작페이지 구현
  src/web/package.json
  src/web/src/Image/church-4911852_1920.jpg
  src/web/src/Image/church-4911852_640.jpg
  src/web/src/pages/service-intro-page.js
Labels: Front-end

#61 Beta update listpage
  src/web/package.json
  src/web/src/components/MediaList/MediaCard.js
  src/web/src/pages/MediaListPage.js
Labels: Front-end, enhancement

#64 cache 문제 해결
  src/web/src/pages/MediaListPage.js
  src/web/src/pages/UploadPage.js
Labels: Front-end, enhancement

#65 medialist 컴포넌트화
  src/web/package-lock.json
  src/web/src/App.js
  src/web/src/components/Header.js
  src/web/src/components/Header/header-icons.js
  src/web/src/components/Header/header-logo.js
  src/web/src/components/Header/header.js
  src/web/src/components/Media/media-card.js
  src/web/src/components/Media/media-detail-card-query.js
  src/web/src/components/Media/media-detail-card.js
  src/web/src/components/Media/media-detail-delete-button.js
  src/web/src/components/Media/media-list.js
  src/web/src/components/MediaList/MediaCard.js
  src/web/src/components/SearchBar/search-bar-input.js
  src/web/src/components/SearchBar/search-bar-place-select.js
  src/web/src/components/SearchBar/search-bar-submit-button.js
  src/web/src/components/SearchBar/search-bar-year-select.js
  src/web/src/components/SearchBar/search-bar.js
  src/web/src/components/SearchBar/service-intro.js
  src/web/src/components/SearchBarPlaceSelect.js
  src/web/src/components/SearchBarSubmitButton.js
  src/web/src/components/UploadPage/DropzoneBox.js
  src/web/src/components/UploadPage/UploadDateSelect.js
  src/web/src/components/UploadPage/UploadDescription.js
  src/web/src/components/UploadPage/UploadPageTitle.js
  src/web/src/components/UploadPage/UploadPlaceSelect.js
  src/web/src/components/UploadPage/UploadSubmitButton.js
  src/web/src/components/UploadPage/dropzone-box.js
  src/web/src/components/UploadPage/upload-date-select.js
  src/web/src/components/UploadPage/upload-description.js
  src/web/src/components/UploadPage/upload-page-title.js
  src/web/src/components/UploadPage/upload-place-select.js
  src/web/src/components/UploadPage/upload-submit-button.js
  src/web/src/components/error-view.js
  src/web/src/components/media-detail-card-query.js
  src/web/src/components/media-detail-delete-button.js
  src/web/src/font.css
  src/web/src/fonts/NanumPenScript-Regular.ttf
  src/web/src/pages/MediaListPage.js
  src/web/src/pages/home-page.js
Labels: Front-end

#66 베타 요구사항 반영
  src/server/app.py
  src/server/mock_data.py
  src/server/resolvers/mutation.py
  src/server/resolvers/query.py
  src/server/resolvers/video.py
  src/server/schema.graphql
Labels: Back-end

#68 date->year로 변경
  src/web/src/components/UploadPage/upload-year-select.js
  src/web/src/pages/upload-page.js
Labels: Front-end

#76 function으로 바꾸고 빈칸 삭제
  src/web/src/components/Media/media-detail-card.js
  src/web/src/pages/upload-page.js
Labels: Front-end

#78 class → function으로 수정
  src/web/src/components/Header/header-icons.js
  src/web/src/components/Header/header-logo.js
  src/web/src/components/Header/header.js
  src/web/src/components/SearchBar/search-bar-input.js
  src/web/src/components/SearchBar/search-bar-place-select.js
  src/web/src/components/SearchBar/search-bar-submit-button.js
  src/web/src/components/SearchBar/search-bar-year-select.js
  src/web/src/components/SearchBar/search-bar.js
Labels: Front-end, enhancement

#79 location options constant화
  src/web/src/App.test.js
  src/web/src/components/SearchBar/search-bar-place-select.js
  src/web/src/components/UploadPage/upload-place-select.js
  src/web/src/components/constants.js
Labels: Front-end

#77 change from class to function
  src/web/src/components/Media/media-card.js
Labels: Front-end, enhancement
