Repository kookmin-sw/capstone-2020-12, pull requests merged in 2020-10, with the labels that each got.

#163 Refactor(server) re naming #155
  src/server/data-sources.js
  src/server/migrations/20201009173516_rename_body_to_content.js
  src/server/resolvers/comment.js
  src/server/resolvers/mutation.js
  src/server/schema.js
  src/server/seeds/mock_data.js
  src/web/src/components/Media/MediaComment/media-add-comment.js
  src/web/src/components/Media/MediaComment/media-comment-list.js
  src/web/src/components/Media/MediaComment/media-comment.js
  src/web/src/components/Media/MediaComment/media-delete-comment.js
  src/web/src/components/Media/MediaComment/media-modify-comment.js
Labels: Back-end, refactoring

#164 refactor: Remove redundant code
  src/server/media_enhancement_module/app.py
Labels: Back-end, refactoring

#165 remove redundant code, remove flag variable and change request code
  src/server/media_enhancement_module/image_colorization_module/app.py
  src/server/media_enhancement_module/image_super_resolution_module/app.py
  src/server/media_enhancement_module/research/colorization/main_whole_up.py
  src/server/media_enhancement_module/research/colorization/myflowlib_up.py
  src/server/media_enhancement_module/research/colorization/preprocess/change_conv2d.py
  src/server/media_enhancement_module/research/colorization/preprocess/video_resolution.py
  src/server/media_enhancement_module/research/colorization/pytorch_pwc/flowlib.py
  src/server/media_enhancement_module/research/colorization/pytorch_pwc/run.py
  src/server/media_enhancement_module/research/colorization/pytorch_pwc/run_data.py
  src/server/media_enhancement_module/research/colorization/utils_up.py
  src/server/media_enhancement_module/video_colorization_module/app.py
  src/server/media_enhancement_module/video_preprocessing_module/app.py
  src/server/media_enhancement_module/video_super_resolution_and_frame_interpolation_module/app.py
Labels: Back-end, refactoring

#170 refactor: specify tag of postres image
  src/server/docker-compose.yml
Labels: refactoring

#168 Refactor(server) set category key based on id #158
  src/server/resolvers/enums.js
  src/server/resolvers/media.js
  src/server/resolvers/mutation.js
Labels: Back-end, javascript, refactoring

#171 Data history
  src/server/data-sources.js
  src/server/migrations/20201018184827_user_active_flag.js
Labels: Back-end, refactoring

#173 Category to tag
  src/server/data-sources.js
  src/server/index.js
  src/server/migrations/20201015222316_change_category_to_tag.js
  src/server/resolvers/media.js
  src/server/resolvers/mutation.js
  src/server/resolvers/query.js
  src/server/resolvers/tag.js
  src/server/schema.js
Labels: Back-end, refactoring

#177 Implement function deactivate user
  src/server/data-sources.js
  src/server/migrations/20201018184827_user_active_flag.js
  src/server/resolvers/mutation.js
  src/server/resolvers/user.js
  src/server/schema.js
Labels: Back-end, enhancement, refactoring

#178 Media activeflag
  src/server/data-sources.js
  src/server/migrations/20201029161500_media_active_flag.js
Labels: Back-end, refactoring
