Repository kookmin-sw/capstone-2020-12, pull requests merged in 2020-05, with the labels that each got.

#92 V1.0 login
  src/web/package-lock.json
  src/web/package.json
  src/web/src/App.js
  src/web/src/components/Header/header-icons.js
  src/web/src/components/SignPage/login-page-button.js
  src/web/src/components/SignPage/register-page-button.js
  src/web/src/components/SignPage/register-page-name.js
  src/web/src/components/SignPage/sign-page-email.js
  src/web/src/components/SignPage/sign-page-password.js
  src/web/src/pages/login-page.js
  src/web/src/pages/register-page.js
Labels: Front-end

#93 Refactoring test
  src/server/static/asset-manifest.json
  src/server/static/css/2.556727a0.chunk.css
  src/server/static/css/2.556727a0.chunk.css.map
  src/server/static/css/main.204443fc.chunk.css
  src/server/static/css/main.204443fc.chunk.css.map
  src/server/static/favicon.ico
  src/server/static/index.html
  src/server/static/js/2.461afee3.chunk.js
  src/server/static/js/2.461afee3.chunk.js.LICENSE.txt
  src/server/static/js/2.461afee3.chunk.js.map
  src/server/static/js/main.268bbeaf.chunk.js
  src/server/static/js/main.268bbeaf.chunk.js.map
  src/server/static/js/runtime-main.3ce8a40d.js
  src/server/static/js/runtime-main.3ce8a40d.js.map
  src/server/static/logo192.png
  src/server/static/logo512.png
  src/server/static/manifest.json
  src/server/static/media/NanumPenScript-Regular.6238324b.ttf
  src/server/static/media/logo.b1c62000.png
  src/server/static/media/roboto-latin-100.5cb7edfc.woff
  src/server/static/media/roboto-latin-100.7370c367.woff2
  src/server/static/media/roboto-latin-100italic.f8b1df51.woff2
  src/server/static/media/roboto-latin-100italic.f9e8e590.woff
  src/server/static/media/roboto-latin-300.b00849e0.woff
  src/server/static/media/roboto-latin-300.ef7c6637.woff2
  src/server/static/media/roboto-latin-300italic.14286f3b.woff2
  src/server/static/media/roboto-latin-300italic.4df32891.woff
  src/server/static/media/roboto-latin-400.479970ff.woff2
  src/server/static/media/roboto-latin-400.60fa3c06.woff
  src/server/static/media/roboto-latin-400italic.51521a2a.woff2
  src/server/static/media/roboto-latin-400italic.fe65b833.woff
  src/server/static/media/roboto-latin-500.020c97dc.woff2
  src/server/static/media/roboto-latin-500.87284894.woff
  src/server/static/media/roboto-latin-500italic.288ad9c6.woff
  src/server/static/media/roboto-latin-500italic.db4a2a23.woff2
  src/server/static/media/roboto-latin-700.2735a3a6.woff2
  src/server/static/media/roboto-latin-700.adcde98f.woff
  src/server/static/media/roboto-latin-700italic.81f57861.woff
  src/server/static/media/roboto-latin-700italic.da0e7178.woff2
  src/server/static/media/roboto-latin-900.9b3766ef.woff2
  src/server/static/media/roboto-latin-900.bb1e4dc6.woff
  src/server/static/media/roboto-latin-900italic.28f91510.woff
  src/server/static/media/roboto-latin-900italic.ebf6d164.woff2
  src/server/static/precache-manifest.8613462b66fa653976b95bba48758dca.js
  src/server/static/robots.txt
  src/server/static/service-worker.js
  src/web/src/App.js
  src/web/src/pages/home-page.js
  src/web/src/pages/media-list-page.js
  src/web/src/pages/media-view-page.js
  src/web/src/pages/upload-page.js
Labels: Front-end, enhancement

#94 V1.0 login
  src/web/src/App.js
  src/web/src/components/Header/header-icons-loginButton.js
  src/web/src/components/Header/header-icons-uploadButton.js
  src/web/src/components/Header/header-icons-userMenu.js
  src/web/src/components/Header/header-icons.js
  src/web/src/components/Header/header.js
  src/web/src/components/Media/media-detail-card-query.js
  src/web/src/pages/login-page.js
  src/web/src/pages/media-view-page.js
  src/web/src/pages/register-page.js
Labels: Front-end, enhancement

#99 createComment, deleteMutation 구현
  src/server/data-sources.js
  src/server/resolvers/comment.js
  src/server/resolvers/mutation.js
  src/server/schema.js
Labels: Back-end, important

#98 V1.0 user page
  src/web/src/App.js
  src/web/src/components/Header/header-icons-userMenu.js
  src/web/src/components/Media/media-list.js
  src/web/src/components/Media/media-search-query.js
  src/web/src/pages/home-page.js
  src/web/src/pages/media-list-page.js
  src/web/src/pages/user-page.js
Labels: Front-end, enhancement

#103 V1.0 pinterest
  src/web/src/components/Media/background.css
  src/web/src/components/Media/media-card.js
  src/web/src/components/Media/user-media-card.js
  src/web/src/components/Media/user-media-list.js
  src/web/src/pages/user-page.js
Labels: Front-end, enhancement

#104 V1.0 detail and upload
  src/web/package-lock.json
  src/web/package.json
  src/web/src/App.js
  src/web/src/components/Media/media-detail-card-image-compare.js
  src/web/src/components/Media/media-detail-card-query.js
  src/web/src/components/Media/media-detail-card.js
  src/web/src/components/Media/media-detail-delete-button.js
  src/web/src/components/Media/media-list.js
  src/web/src/components/Media/media-search-query.js
  src/web/src/components/Media/service-intro.js
  src/web/src/components/ReactCompareImage/ReactCompareImage.js
  src/web/src/components/UploadPage/dropzone-box.js
  src/web/src/components/UploadPage/upload-category-select.js
  src/web/src/components/UploadPage/upload-description.js
  src/web/src/components/UploadPage/upload-page-title.js
  src/web/src/components/UploadPage/upload-place-select.js
  src/web/src/components/UploadPage/upload-submit-button.js
  src/web/src/components/UploadPage/upload-year-select.js
  src/web/src/components/constants.js
  src/web/src/components/error-view.js
  src/web/src/pages/upload-page.js
Labels: Front-end

#105 V1.0 update
  src/web/src/App.js
  src/web/src/components/Header/header-icons-uploadButton.js
  src/web/src/components/Header/header-icons-userMenu.js
  src/web/src/components/Header/header.js
  src/web/src/components/Media/media-card.js
  src/web/src/components/Media/media-detail-card-query.js
  src/web/src/components/Media/media-list.js
  src/web/src/components/Media/media-search-query.js
  src/web/src/components/Media/user-media-card.js
  src/web/src/components/Media/user-media-list.js
  src/web/src/components/UploadPage/upload-description.js
  src/web/src/components/UserPage/user-media-card.js
  src/web/src/components/UserPage/user-media-deleteButton.js
  src/web/src/pages/media-view-page.js
  src/web/src/pages/user-page.js
Labels: Front-end, enhancement

#107 V1.0 update
  src/web/src/components/Header/header-icons-userMenu.js
  src/web/src/pages/media-view-page.js
  src/web/src/pages/user-page.js
Labels: Front-end, bug

#108 V1.0 responsive
  src/web/src/components/Header/header-icons-uploadButton.js
  src/web/src/components/Header/header-icons.js
  src/web/src/components/Header/header.js
  src/web/src/components/Media/media-card.js
  src/web/src/components/SearchBar/search-bar.js
Labels: Front-end, enhancement

#110 Deoldify Colorization
  doc/회의록/200501_회의록(20차).pdf
  doc/회의록/200508_회의록(21차).pdf
  doc/회의록/200511_회의록(22차).pdf
  doc/회의록/200516_회의록(23차).pdf
  src/server/media_enhancement_module/image_colorization/ColorFIDBenchmarkArtistic.ipynb
  src/server/media_enhancement_module/image_colorization/ColorizeTrainingArtistic.ipynb
  src/server/media_enhancement_module/image_colorization/ColorizeTrainingStable.ipynb
  src/server/media_enhancement_module/image_colorization/ColorizeTrainingStableLargeBatch.ipynb
  src/server/media_enhancement_module/image_colorization/ColorizeTrainingVideo.ipynb
  src/server/media_enhancement_module/image_colorization/ColorizeTrainingWandb.ipynb
  src/server/media_enhancement_module/image_colorization/Dockerfile
  src/server/media_enhancement_module/image_colorization/Dockerfile-api
  src/server/media_enhancement_module/image_colorization/ImageColorizer.ipynb
  src/server/media_enhancement_module/image_colorization/ImageColorizerArtisticTests.ipynb
  src/server/media_enhancement_module/image_colorization/ImageColorizerColab.ipynb
  src/server/media_enhancement_module/image_colorization/ImageColorizerColabStable.ipynb
  src/server/media_enhancement_module/image_colorization/ImageColorizerStableTests.ipynb
  src/server/media_enhancement_module/image_colorization/LICENSE
  src/server/media_enhancement_module/image_colorization/MANIFEST.in
  src/server/media_enhancement_module/image_colorization/README.md
  src/server/media_enhancement_module/image_colorization/VideoColorizer.ipynb
  src/server/media_enhancement_module/image_colorization/VideoColorizerColab.ipynb
  src/server/media_enhancement_module/image_colorization/app-video.py
  src/server/media_enhancement_module/image_colorization/app.py
  src/server/media_enhancement_module/image_colorization/app_utils.py
  src/server/media_enhancement_module/image_colorization/colab_requirements.txt
  src/server/media_enhancement_module/image_colorization/deoldify/__init__.py
  src/server/media_enhancement_module/image_colorization/deoldify/_device.py
  src/server/media_enhancement_module/image_colorization/deoldify/augs.py
  src/server/media_enhancement_module/image_colorization/deoldify/critics.py
  src/server/media_enhancement_module/image_colorization/deoldify/dataset.py
  src/server/media_enhancement_module/image_colorization/deoldify/device_id.py
  src/server/media_enhancement_module/image_colorization/deoldify/filters.py
  src/server/media_enhancement_module/image_colorization/deoldify/generators.py
  src/server/media_enhancement_module/image_colorization/deoldify/layers.py
  src/server/media_enhancement_module/image_colorization/deoldify/loss.py
  src/server/media_enhancement_module/image_colorization/deoldify/save.py
  src/server/media_enhancement_module/image_colorization/deoldify/unet.py
  src/server/media_enhancement_module/image_colorization/deoldify/visualize.py
  src/server/media_enhancement_module/image_colorization/environment.yml
  src/server/media_enhancement_module/image_colorization/fid/LICENSE
  src/server/media_enhancement_module/image_colorization/fid/fid_score.py
  src/server/media_enhancement_module/image_colorization/fid/inception.py
  src/server/media_enhancement_module/image_colorization/image_colorize.py
  src/server/media_enhancement_module/image_colorization/requirements-dev.txt
  src/server/media_enhancement_module/image_colorization/requirements.txt
  src/server/media_enhancement_module/image_colorization/resource_images/Twitter_Social_Icon_Rounded_Square_Color.svg
  src/server/media_enhancement_module/image_colorization/resource_images/watermark.png
  src/server/media_enhancement_module/image_colorization/run_notebook.sh
  src/server/media_enhancement_module/image_colorization/set_password.py
  src/server/media_enhancement_module/image_colorization/setup.py
  src/server/media_enhancement_module/image_colorization/test_images/placeholder.txt
  src/server/media_enhancement_module/image_colorization/tox.ini
  src/server/media_enhancement_module/image_colorization/video_colorize.py
Labels: enhancement

#116 타입에 따라서 video나 ImageCompare가 나오도록 수정
  src/web/src/components/Media/media-detail-card-query.js
  src/web/src/components/Media/media-detail-card.js
Labels: Front-end, bug

#117 deoldify 인자 수정
  src/server/media_enhancement_module/image_colorization_module/README.md
  src/server/media_enhancement_module/image_colorization_module/image_colorize.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/README.md
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify/visualize.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/Dockerfile
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/Dockerfile-api
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/LICENSE
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/MANIFEST.in
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/README.md
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/app-video.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/app.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/app_utils.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/__init__.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/_device.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/augs.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/critics.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/dataset.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/device_id.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/filters.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/generators.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/layers.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/loss.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/save.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/unet.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/deoldify/visualize.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/env.yml
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/environment.yml
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/fid/LICENSE
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/fid/fid_score.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/fid/inception.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/image_colorize.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/requirements-dev.txt
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/requirements.txt
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/resource_images/Twitter_Social_Icon_Rounded_Square_Color.svg
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/resource_images/watermark.png
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/run_notebook.sh
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/set_password.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/setup.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/tox.ini
  src/server/media_enhancement_module/video_colorization_deoldify_module/deoldify_colorization/video_colorize.py
  src/server/media_enhancement_module/video_colorization_deoldify_module/video_colorize.py
Labels: bug, enhancement

#120 V1.0 debug
  src/web/src/Image/placeholder.jpg
  src/web/src/components/Media/media-card.js
  src/web/src/components/Media/media-list.js
  src/web/src/components/Media/media-search-query.js
  src/web/src/pages/media-view-page.js
Labels: Front-end, bug
